name: Build Workflow

# Inputs
inputs:
 branch_name: 
   description: "Current Branch"
   required: true
   default: "main"
 sonarcloud_token:
   description: "Token For Sonarcloud"
   required: true
 sonarcloud_host_url:     
   description: "Sonarcloud Host URL"
   required: true
 sonarcloud_organization:
   description: "Organization Name on Sonarcloud "
   required: true
 sonarcloud_sources:
   description: "source folder"
   required: true   
 sonarcloud_projectKey:
   description: "Sonar project key"
   required: true
 sonarcloud_coverage_jacoco_xmlReportPaths:
   description: "Jacoco reports path"
   required: true
 sonarcloud_java_binaries:
   description: "Java binaries folder"
   required: true         
 sonarcloud_tests:
   description: "Java test folder"
   required: true                

run-name: 'Build Workflow -- ${{ github.head_ref || github.ref_name }}'

on:
    push:
    pull_request:
    workflow_dispatch:

env:
  MAVEN_SETTING: '/home/ec2-user/maven/.m2/settings.xml'
  BRANCH_NAME: ${{github.ref_name}}

jobs:
  build-job:
    name: Build Job
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/setup-java@v4
        with:
            java-version: '21'
            distribution: 'zulu'
      - name: Build IKMDEV Code
        uses: casaras1/maven-clean-install-build-action@main
        with:
          branch_name: ${{env.BRANCH_NAME}}
          sonarcloud_token: ${{ secrets.SONAR_TOKEN }}
          sonarcloud_host_url: ${{ 'https://sonarcloud.io/' }}
          sonarcloud_organization: ${{ github.repository_owner }}
          sonarcloud_sources: ${{ 'src/main/java' }}
          sonarcloud_projectKey: ${{ github.repository_owner }}_${{ github.event.repository.name }}
          sonarcloud_coverage_jacoco_xmlReportPaths: ${{ 'target/site/jacoco/jacoco.xml' }}
          sonarcloud_java_binaries: ${{ 'target/classes' }}
